server:
  port: 8083

spring:
  application:
    name: file-management

  datasource:
    url: jdbc:postgresql://localhost:5432/courseland-files
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
        ddl-auto: none
    generate-ddl: false

  servlet:
    multipart:
      maxFileSize: 20MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true