server:
  port: 8081

spring:
  application:
    name: app-user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/courseland-users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
        ddl-auto: none
    generate-ddl: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true